export const COMPONENTS_SUMMARY_JP = {
    "Accordion": "複数のセクションを折りたたみ式で表示する。各セクションはヘッダーをクリックすることで展開・折りたたみが可能。大量の情報を整理して表示する際に便利。",
    "Box": "コンテンツをラップするための基本的なコンテナ。幅、高さ、背景色、ボーダー、WebkitCSSなどのスタイルを自由に設定可能。汎用的なレイアウト要素として使用。",
    "Card": "情報をカード形式で表示する。角丸、背景色、影（elevation）、WebkitCSSなどを設定可能。情報を視覚的にグループ化して表示するのに適している。",
    "Center": "子要素を水平・垂直方向に中央揃えする。子要素のサイズに関わらず、常に中央に配置される。レスポンシブデザインにも対応。",
    "Chips": "小さなラベルや情報を表示する。タグやカテゴリ、ステータスなどを簡潔に表示するのに適している。カスタマイズ可能なスタイルオプションを提供。",
    "Clip": "コンテンツをクリップするためのラッパー。指定した形状や範囲で子要素を切り抜いて表示する。画像や動画の一部を切り出す際に使用。",
    "CodeBlock": "コードブロックを表示し、シンタックスハイライトや行番号表示などの機能を提供する。プログラミングコードのスニペットを表示する際に利用。",
    "Column": "縦方向にレイアウトするためのコンテナ。子要素を垂直方向に並べて表示する。水平方向の中央揃えも可能。レスポンシブなカラムレイアウトを実現。",
    "DropDownMenu": "選択肢をドロップダウン形式で表示する。ユーザーが選択可能なオプションリストを提供。フォームやナビゲーションメニューに利用。",
    "ElevatedButton": "浮き上がり効果のあるインタラクティブなボタン。クリック時に視覚的なフィードバックを提供。アクションの実行やフォームの送信に使用。",
    "ExpandsPanel": "コンテンツを展開・折りたたみ可能なパネル。詳細情報を必要に応じて表示・非表示にできる。FAQや設定画面などで利用。",
    "FloatingActionButton": "画面下部に固定表示される円形のアクションボタン。主要なアクションを常にアクセス可能にする。モバイルアプリなどでよく使用される。",
    "Grid": "グリッドレイアウトを実現するためのコンテナ。子要素をグリッド状に配置し、複雑なレイアウトを容易に作成。レスポンシブグリッドにも対応。",
    "Header": "ページやセクションのヘッダー部分を表現する。タイトルやナビゲーション要素を含む。ページの構造を明確にするために使用。",
    "Hover": "マウスホバー時の効果を適用する。子要素にマウスが乗った際にスタイルを変更。インタラクティブなUIを実現。",
    "Image": "画像を表示するためのラッパー。画像のソース、代替テキスト、タイトル、スタイルなどを設定可能。レスポンシブ画像にも対応。",
    "LimitedProviderScope": "スコープを制限したプロバイダーのラッパー。特定の範囲内でのみプロバイダーの値を利用可能にする。状態管理を局所化。",
    "Link": "クリック可能なリンクを表現する。外部サイトへの遷移やページ内リンクに使用。ダウンロード属性やターゲット属性も設定可能。",
    "Margin": "子要素にマージンを適用する。要素間のスペースを調整し、レイアウトを整える。レスポンシブなマージン設定も可能。",
    "Padding": "子要素にパディングを適用する。要素内部のスペースを調整し、コンテンツを見やすくする。レスポンシブなパディング設定も可能。",
    "PageRouter": "ページ間の遷移を管理する。シングルページアプリケーション（SPA）などでページ遷移を制御。",
    "Paginations": "ページング機能を提供する。大量のデータを分割して表示し、ユーザーがページを移動できるようにする。テーブルやリストなどで使用。",
    "Position": "子要素の位置を制御する。絶対配置や相対配置を使用して、子要素を任意の位置に配置。重ね合わせや複雑なレイアウトに利用。",
    "RadioButton": "一つだけを選択可能な選択肢のグループ。フォームなどで排他的な選択肢を提供。ユーザーは一つのオプションのみ選択可能。",
    "RelativePosition": "相対的な位置関係を定義する。親要素を基準とした相対的な位置に子要素を配置。レイアウトの柔軟性を高める。",
    "Row": "横方向にレイアウトするためのコンテナ。子要素を水平方向に並べて表示する。中央揃えやスペース配分も可能。レスポンシブな行レイアウトを実現。",
    "Scaffold": "基本的なページ構造を提供する。ヘッダー、フッター、サイドバーなどを含む基本的なレイアウトを提供する。ページ全体の構造を統一。",
    "Shrink": "子要素を収縮させる。子要素が親要素のサイズを超えた場合に、自動的に縮小して表示。レスポンシブなレイアウトに利用。",
    "SimpleDialog": "モーダル形式のダイアログを表示する。ユーザーに重要な情報や選択肢を提示。アラートや確認ダイアログなどに使用。",
    "Slider": "値をスライドして選択する。範囲内の値を連続的に選択できる。フォームや設定画面で利用。",
    "SpaceBox": "均等なスペースで子要素を配置する。指定した幅や高さのスペースを挿入し、レイアウトの調整を行う。",
    "Stack": "子要素をスタック形式で配置する。子要素を重ねて表示し、レイヤー構造を作成。画像やテキストの重ね合わせに利用。",
    "Text": "テキストをスタイリングするためのラッパー。フォント、色、サイズ、スタイルなどを自由に設定可能。WebkitCSSもサポート。",
    "TextArea": "複数行のテキスト入力を可能にする。フォームなどで長文の入力を受け付ける。テキストの折り返しやスクロールも可能。",
    "TextForm": "フォーム用のテキスト入力フィールドを提供する。テキストの入力、編集、検証を行うためのフィールド。ラベルやプレースホルダーも設定可能。"
};

export const COMPONENTS_SUMMARY_EN = {
    "Accordion": "Displays multiple collapsible sections. Each section can be expanded or collapsed by clicking its header, ideal for organizing large amounts of information.",
    "Box": "A basic container for wrapping content. Offers customizable width, height, background color, border, and WebkitCSS styles. Versatile layout element.",
    "Card": "Presents information in a card format with customizable corner radius, background color, elevation (shadow), and WebkitCSS. Visually groups information effectively.",
    "Center": "Horizontally and vertically centers child elements, ensuring they are always positioned in the middle, regardless of size. Supports responsive design.",
    "Chips": "Displays small labels or pieces of information, suitable for tags, categories, or statuses. Offers customizable styling options.",
    "Clip": "Wraps content and clips it to a specified shape or area, useful for cropping images or videos.",
    "CodeBlock": "Displays code blocks with syntax highlighting and line numbering, ideal for showcasing programming code snippets.",
    "Column": "A container for vertical layouts, arranging child elements in a top-to-bottom order. Supports horizontal centering for responsive column layouts.",
    "DropDownMenu": "Presents a list of selectable options in a dropdown format, commonly used in forms or navigation menus.",
    "ElevatedButton": "An interactive button with a visual elevation effect, providing feedback upon click. Used for actions and form submissions.",
    "ExpandsPanel": "A panel that can expand or collapse to show or hide detailed information, ideal for FAQs and settings screens.",
    "FloatingActionButton": "A circular action button fixed at the bottom of the screen, providing constant access to primary actions, commonly used in mobile apps.",
    "Grid": "A container for grid layouts, arranging child elements in a grid pattern to create complex layouts. Supports responsive grids.",
    "Header": "Represents the header of a page or section, containing titles and navigation elements to clarify page structure.",
    "Hover": "Applies effects when the mouse hovers over child elements, enhancing UI interactivity.",
    "Image": "A wrapper for displaying images with customizable source, alt text, title, and styles. Supports responsive images.",
    "LimitedProviderScope": "A wrapper that limits the scope of providers, allowing their values to be used only within a specific area. Useful for localizing state management.",
    "Link": "Represents clickable links for navigating to external sites or within the page, with options for download and target attributes.",
    "Margin": "Applies margins to child elements, adjusting spacing for better layout. Supports responsive margin settings.",
    "Padding": "Applies padding to child elements, adjusting internal spacing for better content presentation. Supports responsive padding settings.",
    "PageRouter": "Manages page transitions in single-page applications (SPAs).",
    "Paginations": "Provides pagination functionality, dividing large datasets into pages for easy navigation in tables or lists.",
    "Position": "Controls the position of child elements using absolute or relative positioning, enabling complex layouts and overlays.",
    "RadioButton": "A group of mutually exclusive options, allowing users to select only one option in forms.",
    "RelativePosition": "Defines relative positioning based on the parent element, enhancing layout flexibility.",
    "Row": "A container for horizontal layouts, arranging child elements in a left-to-right order. Supports centering and space distribution for responsive row layouts.",
    "Scaffold": "Provides a basic page structure with headers, footers, and sidebars, ensuring consistent page layouts.",
    "Shrink": "Automatically shrinks child elements to fit within the parent container, useful for responsive layouts.",
    "SimpleDialog": "Displays modal dialogs for important information or choices, such as alerts and confirmations.",
    "Slider": "Allows users to select values within a range by sliding, commonly used in forms and settings screens.",
    "SpaceBox": "Inserts fixed-size spaces between child elements, adjusting layout spacing.",
    "Stack": "Arranges child elements in a stacked manner, creating layered structures for overlapping images or text.",
    "Text": "A wrapper for styling text with customizable font, color, size, and styles. Supports WebkitCSS.",
    "TextArea": "Enables multi-line text input in forms, supporting text wrapping and scrolling.",
    "TextForm": "Provides text input fields for forms with labeling and placeholder support, facilitating text input, editing, and validation."
};
